name: env parent file

on:
  push:
    branches:
      - main

jobs:
  testiub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Import
        run: |
          curl -H "Authorization: token ${{secrets.TOKEN}}" -L -o otherepo.env https://github.com/kpnssreeram/resuseworkflow-composite/blob/main/otherepo.env
              
      - name: Print
        run: ls
