name: env parent file

on:
  push:
    branches:
      - main

jobs:
  testiub:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Another Repo
        uses: actions/checkout@v4
        with:
          repository: kpnssreeram/resuseworkflow-composite  # Replace with the actual username and repository name
          path: resuseworkflow-composite # Specify a subdirectory to checkout the repository, if needed
          token: ${{ secrets.TOKEN }}
          
      - name: Copy File to Current Directory
        run: cp resuseworkflow-composite/otherepo.env .

      # Continue with the rest of your workflow using the downloaded file
      - name: Use Downloaded File
        run: cat otherepo.env 
             
      # - name: Import
      #   run: |
      #     curl -L -o otherepo.env https://github.com/kpnssreeram/resuseworkflow-composite/blob/main/otherepo.env

      
      - name: Print
        run: |
             ls
        
      - name: impenvfile
        uses: cardinalby/export-env-action@v2
        with:
          envFile: otherepo.env
          expand: true
    
      - name: Printing env
        run: |
             cat otherepo.env
             echo "${{env.name}}"


          
   
