name: env parent file

on:
  push:
    branches:
      - main

jobs:
  testiub:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Checkout Another Repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: kpnssreeram/resuseworkflow-composite 
      #     path: resuseworkflow-composite 
      #     token: ${{ secrets.TOKEN }}
          
      # - name: Copy File 
      #   run: cp resuseworkflow-composite/hello.env .

      # - name: Upload math result for job 1
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: envcopy
      #     path: hello.env

          
      # - name: Downloaded File
      #   run: cat hello.env 
             
      - name: Import
        run: |
           curl -LJO https://github.com/kpnssreeram/resuseworkflow-composite/blob/main/hello.env
          # curl -L -o otherepo.env https://github.com/kpnssreeram/resuseworkflow-composite/blob/main/otherepo.env
    
      - name: Print
        run: |
             ls
             # cd resuseworkflow-composite
             ls

        
      - name: Import
        uses: cardinalby/export-env-action@v2
        with:
          envFile: 'hello.env'
          expand: 'true'
    
      - name: Printing env
        run: |
              cat hello.env
               echo "${{ env.name }}"
        
  thisrepo:
      runs-on: ubuntu-latest
      needs: testiub
      steps:
        - name: Checkout this Repo
          uses: actions/checkout@v4
          
        - name: Download math result for job 1
          uses: actions/download-artifact@v1
          with:
            name: envcopy
        
        - name: Import
          uses: cardinalby/export-env-action@v2
          with:
            envFile: 'envcopy/hello.env'
            expand: 'true'

        - name: Printing env
          run: |
              cat hello.env
              echo "${{ env.name }}"
        

        
        - name: Printing env
          run: echo "${{ env.name }}"
          
