name: env parent file

on:
  push:
    branches:
      - main

jobs:
  testiub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import
        uses: cardinalby/export-env-action@v2
        with:
          envFile: 'kpnssreeram/resuseworkflow-composite/otherepo.env@main'
          expand: 'true'

      - name: Print
        run: echo "${{ env.name }}"
